name: Stock Analysis Automator

on:
  schedule:
    - cron: '30 21 * * *'
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas gspread google-auth google-auth-oauthlib requests yfinance openpyxl

      - name: Run Analysis Script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
        run: |
          echo "★スクリプト実行を開始します"
          python adogem1.py 4000 4500
          echo "★スクリプト実行が完了しました"
