name: adoGEM Full Scan Continuous

on:
  schedule:
    - cron: '40 19 * * 2-6' # 火〜土の朝4:40（日本時間）に実行
  workflow_dispatch: # 手動実行ボタン

jobs:
  scan-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread google-auth lxml html5lib requests yfinance openpyxl

      - name: Run CSV Download & Analysis
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
        run: |
          python adogem1.py 4000 4500
